// This file is auto-generated by @hey-api/openapi-ts

export const CommentSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        body: {
            type: 'string',
            title: 'Body'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp',
            default: '2024-11-15T14:03:37.132195'
        },
        author_id: {
            type: 'integer',
            title: 'Author Id'
        },
        post_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Post Id'
        }
    },
    type: 'object',
    required: ['body'],
    title: 'Comment'
} as const;

export const GroupSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        creation_date: {
            type: 'string',
            format: 'date-time',
            title: 'Creation Date',
            default: '2024-11-15T14:03:37.114830'
        },
        creator_id: {
            type: 'integer',
            title: 'Creator Id'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Group'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LikeSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp',
            default: '2024-11-15T14:03:37.133786'
        },
        author_id: {
            type: 'integer',
            title: 'Author Id'
        },
        post_id: {
            type: 'integer',
            title: 'Post Id'
        }
    },
    type: 'object',
    title: 'Like'
} as const;

export const PostSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        body: {
            type: 'string',
            title: 'Body'
        },
        external_content_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Content Url'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp',
            default: '2024-11-15T14:03:37.116359'
        },
        author_id: {
            type: 'integer',
            title: 'Author Id'
        },
        group_id: {
            type: 'integer',
            title: 'Group Id'
        }
    },
    type: 'object',
    required: ['body', 'external_content_url'],
    title: 'Post'
} as const;

export const UserSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password_hash: {
            type: 'string',
            title: 'Password Hash'
        },
        registered_at: {
            type: 'string',
            format: 'date-time',
            title: 'Registered At',
            default: '2024-11-15T14:03:37.111762'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        bio: {
            type: 'string',
            title: 'Bio'
        }
    },
    type: 'object',
    required: ['email', 'password_hash', 'name', 'bio'],
    title: 'User'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;