// This file is auto-generated by @hey-api/openapi-ts

export type Comment = {
    id?: (number | null);
    body: string;
    timestamp?: string;
    author_id?: number;
    post_id?: (number | null);
};

export type Group = {
    id?: (number | null);
    name: string;
    description?: (string | null);
    creation_date?: string;
    creator_id?: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Like = {
    id?: (number | null);
    timestamp?: string;
    author_id?: number;
    post_id?: number;
};

export type Post = {
    id?: (number | null);
    body: string;
    external_content_url: (string | null);
    timestamp?: string;
    author_id?: number;
    group_id?: number;
};

export type User = {
    id?: (number | null);
    email: string;
    password_hash: string;
    registered_at?: string;
    name: string;
    bio: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type HealthcheckGetResponse = (unknown);

export type HealthcheckGetError = unknown;

export type GetAllUsersUserGetResponse = (unknown);

export type GetAllUsersUserGetError = unknown;

export type CreateUserUserPostData = {
    body: User;
};

export type CreateUserUserPostResponse = (unknown);

export type CreateUserUserPostError = (HTTPValidationError);

export type GetUserByIdUserUserIdGetData = {
    path: {
        user_id: number;
    };
};

export type GetUserByIdUserUserIdGetResponse = (unknown);

export type GetUserByIdUserUserIdGetError = (HTTPValidationError);

export type GetMemberGroupsByUserIdUserUserIdGroupsGetData = {
    path: {
        user_id: number;
    };
};

export type GetMemberGroupsByUserIdUserUserIdGroupsGetResponse = (unknown);

export type GetMemberGroupsByUserIdUserUserIdGroupsGetError = (HTTPValidationError);

export type CreateGroupGroupPostData = {
    body: Group;
};

export type CreateGroupGroupPostResponse = (unknown);

export type CreateGroupGroupPostError = (HTTPValidationError);

export type GetGroupByIdGroupGroupIdGetData = {
    path: {
        group_id: number;
    };
};

export type GetGroupByIdGroupGroupIdGetResponse = (unknown);

export type GetGroupByIdGroupGroupIdGetError = (HTTPValidationError);

export type CreatePostPostPostData = {
    body: Post;
};

export type CreatePostPostPostResponse = (unknown);

export type CreatePostPostPostError = (HTTPValidationError);

export type GetPostByIdPostPostIdGetData = {
    path: {
        post_id: number;
    };
};

export type GetPostByIdPostPostIdGetResponse = (unknown);

export type GetPostByIdPostPostIdGetError = (HTTPValidationError);

export type DeletePostByIdPostPostIdDeleteData = {
    path: {
        post_id: number;
    };
};

export type DeletePostByIdPostPostIdDeleteResponse = (unknown);

export type DeletePostByIdPostPostIdDeleteError = (HTTPValidationError);

export type CreateCommentPostPostIdCommentPostData = {
    body: Comment;
    path: {
        post_id: number;
    };
};

export type CreateCommentPostPostIdCommentPostResponse = (unknown);

export type CreateCommentPostPostIdCommentPostError = (HTTPValidationError);

export type GetCommentsByPostIdPostPostIdCommentGetData = {
    path: {
        post_id: number;
    };
};

export type GetCommentsByPostIdPostPostIdCommentGetResponse = (unknown);

export type GetCommentsByPostIdPostPostIdCommentGetError = (HTTPValidationError);

export type DeleteCommentByIdPostPostIdCommentCommentIdDeleteData = {
    path: {
        comment_id: number;
        post_id: number;
    };
};

export type DeleteCommentByIdPostPostIdCommentCommentIdDeleteResponse = (unknown);

export type DeleteCommentByIdPostPostIdCommentCommentIdDeleteError = (HTTPValidationError);

export type LikePostPostPostIdLikePostData = {
    body: Like;
    path: {
        post_id: number;
    };
};

export type LikePostPostPostIdLikePostResponse = (unknown);

export type LikePostPostPostIdLikePostError = (HTTPValidationError);

export type GetLikesByPostIdPostPostIdLikeGetData = {
    path: {
        post_id: number;
    };
};

export type GetLikesByPostIdPostPostIdLikeGetResponse = (unknown);

export type GetLikesByPostIdPostPostIdLikeGetError = (HTTPValidationError);

export type RemoveLikesPostsPostIdLikeDeleteData = {
    path: {
        post_id: number;
    };
};

export type RemoveLikesPostsPostIdLikeDeleteResponse = (unknown);

export type RemoveLikesPostsPostIdLikeDeleteError = (HTTPValidationError);

export type GetPostsByUserIdUserUserIdPostsGetData = {
    path: {
        user_id: number;
    };
};

export type GetPostsByUserIdUserUserIdPostsGetResponse = (unknown);

export type GetPostsByUserIdUserUserIdPostsGetError = (HTTPValidationError);

export type JoinGroupUserUserIdGroupsGroupIdJoinPostData = {
    path: {
        group_id: number;
        user_id: number;
    };
};

export type JoinGroupUserUserIdGroupsGroupIdJoinPostResponse = (unknown);

export type JoinGroupUserUserIdGroupsGroupIdJoinPostError = (HTTPValidationError);